import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import puppeteer from 'puppeteer';
import { normalizeSnapshot, getRanking } from '../public/lib/racing.js';

const root = fileURLToPath(new URL('../', import.meta.url));
const out = resolve(root, 'test-results');
await mkdir(out, { recursive: true });
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env: { ...process.env, PORT: '3100' } });
await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(new Error(`Servidor: ${code}`))); });
let browser;
const checks = [];
const catalog = JSON.parse(await readFile(resolve(root, 'public/data/versions.json'), 'utf8'));
const latestSnapshot = normalizeSnapshot(JSON.parse(await readFile(resolve(root, 'public/data', catalog.versions[0].file), 'utf8')));
const previousSnapshot = catalog.versions[1] ? normalizeSnapshot(JSON.parse(await readFile(resolve(root, 'public/data', catalog.versions[1].file), 'utf8'))) : null;
try {
  browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.BROWSER_EXECUTABLE_PATH || undefined,
    pipe: true,
    args: process.env.BROWSER_TEST_CONTAINER === 'true' ? ['--no-sandbox', '--disable-dev-shm-usage', '--single-process', '--no-zygote'] : []
  });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewport({ width: 1440, height: 1080 });
  await page.goto('http://127.0.0.1:3100', { waitUntil: 'networkidle0' });
  await page.waitForSelector('.race-table tbody tr');
  assert.equal(await page.$$eval('.race-table tbody tr', rows => rows.length), 10);
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '1.020');
  assert.equal(await page.$eval('.leader-metric strong', el => el.textContent), 'trustmeson');
  checks.push('Carga de las 1.020 carreras reales y líder correcto');
  await page.screenshot({ path: resolve(out, 'desktop.png'), fullPage: true });
  const first = await page.$eval('.race-name', el => el.textContent);
  await page.click('[data-page="2"]');
  assert.notEqual(await page.$eval('.race-name', el => el.textContent), first);
  checks.push('Paginación');
  await page.select('[data-filter="vehicle"]', 'Uranus');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '33');
  await page.click('#advanced-toggle');
  await page.type('[data-filter="minTime"]', '3:00');
  const rows = await page.$$eval('.race-time', elements => elements.map(el => el.textContent));
  assert.ok(rows.every(time => Number(time.split(':')[0]) >= 3));
  await page.type('[data-filter="maxTime"]', '0:30');
  assert.match(await page.$eval('#filter-error', el => el.textContent), /mínimo/);
  assert.ok(await page.$('.empty-state'));
  checks.push('Filtros combinados y validación de rangos');
  await page.click('#clear-filters');
  await page.type('#race-search', 'no-existe-xyz-999999');
  assert.ok(await page.$('.empty-state'));
  await page.click('#empty-reset');
  await page.click('.favorite-button');
  await page.reload({ waitUntil: 'networkidle0' });
  await page.click('[data-nav="favorites"]');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '1');
  await page.click('.race-name');
  assert.ok(await page.$('dialog[open]'));
  await page.keyboard.press('Escape');
  assert.equal(await page.$('dialog[open]'), null);
  checks.push('Búsqueda vacía, favoritos persistentes y detalle accesible');
  await page.click('[data-nav="garage"]');
  assert.equal(await page.$$eval('.garage-grid .vehicle-card', cards => cards.length), 93);
  await page.type('#garage-search', 'infernus');
  assert.equal(await page.$$eval('.garage-grid .vehicle-card', cards => cards.length), 1);
  await page.click('.garage-grid .vehicle-card');
  assert.equal(await page.$eval('[data-filter="vehicle"]', select => select.value), 'Infernus');
  checks.push('Garaje y acceso a carreras por vehículo');
  await page.click('#clear-filters');
  await page.click('[data-nav="ranking"]');
  assert.equal(await page.$eval('.podium-0 h2', el => el.textContent), 'trustmeson');
  assert.equal(await page.$$eval('.ranking-table tbody tr', rows => rows.length), getRanking(latestSnapshot.races, previousSnapshot?.races).length);
  await page.screenshot({ path: resolve(out, 'ranking.png'), fullPage: true });
  checks.push('Ranking completo con porcentajes');
  assert.equal(await page.$('input[type="file"]'), null);
  assert.equal(await page.$$eval('#snapshot-select option', options => options.length), catalog.versions.length);
  if (catalog.versions.length > 1) {
    assert.match(await page.$eval('.ranking-info', el => el.textContent), /Cambios frente a/);
    const firstVersion = catalog.versions.at(-1).id;
    await page.select('#snapshot-select', firstVersion);
    await page.waitForFunction(() => document.querySelector('.ranking-info')?.textContent.includes('Primer corte disponible'));
    assert.ok(page.url().includes(`snapshot=${firstVersion}`));
    assert.equal(await page.$('.ranking-table .delta'), null);
    await page.reload({ waitUntil: 'networkidle0' });
    assert.equal(await page.$eval('#snapshot-select', select => select.value), firstVersion);
    await page.select('#snapshot-select', catalog.latest);
    await page.waitForFunction(() => document.querySelector('.ranking-info')?.textContent.includes('Cambios frente a'));
    await page.goBack({ waitUntil: 'networkidle0' });
    await page.waitForFunction(id => document.querySelector('#snapshot-select')?.value === id, {}, firstVersion);
    await page.select('#snapshot-select', catalog.latest);
    await page.waitForFunction(() => document.querySelector('.ranking-info')?.textContent.includes('Cambios frente a'));
  }
  checks.push('Versiones publicadas, comparación automática, recarga y navegación atrás');
  await page.click('#data-button');
  assert.match(await page.$eval('#data-dialog', el => el.textContent), /no permite subir archivos/);
  assert.equal(await page.$('#import-current'), null);
  await page.keyboard.press('Escape');
  checks.push('Información de datos solo lectura, sin carga de archivos');
  await page.click('[data-nav="overview"]');
  await page.setViewport({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(out, 'mobile.png'), fullPage: true });
  const size = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
  assert.ok(size.scroll <= size.width, `Desbordamiento móvil: ${JSON.stringify(size)}`);
  await page.click('[data-nav="races"]');
  await page.type('#race-search', 'Voodoo');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '33');
  await page.click('#clear-filters');
  await page.click('.race-name');
  assert.ok(await page.$('dialog[open]'));
  await page.keyboard.press('Escape');
  checks.push('Móvil de 390 px: sin desbordamiento, búsqueda y diálogos');
  const denied = await fetch('http://127.0.0.1:3100/.env');
  assert.equal(denied.status, 403);
  const source = await fetch('http://127.0.0.1:3100/index.js');
  assert.equal(source.status, 404);
  assert.deepEqual(errors, []);
  checks.push('Servidor restringido a archivos públicos y sin errores JS');
  console.log(checks.map((check, i) => `${i + 1}. OK ${check}`).join('\n'));
  await writeFile(resolve(out, 'browser-results.json'), JSON.stringify({ checks, errors }, null, 2));
} finally {
  await browser?.close();
  server.kill();
}
