import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
import puppeteer from 'puppeteer';

const root = fileURLToPath(new URL('../', import.meta.url));
const out = resolve(root, 'test-results');
await mkdir(out, { recursive: true });
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env: { ...process.env, PORT: '3100' } });
await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); server.once('exit', code => reject(new Error(`Servidor: ${code}`))); });
let browser;
const checks = [];
try {
  browser = await puppeteer.launch({
    headless: true,
    executablePath: process.env.BROWSER_EXECUTABLE_PATH || undefined,
    pipe: true,
    args: process.env.BROWSER_TEST_CONTAINER === 'true' ? ['--no-sandbox', '--disable-dev-shm-usage', '--single-process', '--no-zygote'] : []
  });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewport({ width: 1440, height: 1080 });
  await page.goto('http://127.0.0.1:3100', { waitUntil: 'networkidle0' });
  await page.waitForSelector('.race-table tbody tr');
  assert.equal(await page.$$eval('.race-table tbody tr', rows => rows.length), 10);
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '1.020');
  assert.equal(await page.$eval('.leader-metric strong', el => el.textContent), 'trustmeson');
  checks.push('Carga de las 1.020 carreras reales y líder correcto');
  await page.screenshot({ path: resolve(out, 'desktop.png'), fullPage: true });
  const first = await page.$eval('.race-name', el => el.textContent);
  await page.click('[data-page="2"]');
  assert.notEqual(await page.$eval('.race-name', el => el.textContent), first);
  checks.push('Paginación');
  await page.select('[data-filter="vehicle"]', 'Uranus');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '33');
  await page.click('#advanced-toggle');
  await page.type('[data-filter="minTime"]', '3:00');
  const rows = await page.$$eval('.race-time', elements => elements.map(el => el.textContent));
  assert.ok(rows.every(time => Number(time.split(':')[0]) >= 3));
  await page.type('[data-filter="maxTime"]', '0:30');
  assert.match(await page.$eval('#filter-error', el => el.textContent), /mínimo/);
  assert.ok(await page.$('.empty-state'));
  checks.push('Filtros combinados y validación de rangos');
  await page.click('#clear-filters');
  await page.type('#race-search', 'no-existe-xyz-999999');
  assert.ok(await page.$('.empty-state'));
  await page.click('#empty-reset');
  await page.click('.favorite-button');
  await page.reload({ waitUntil: 'networkidle0' });
  await page.click('[data-nav="favorites"]');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '1');
  await page.click('.race-name');
  assert.ok(await page.$('dialog[open]'));
  await page.keyboard.press('Escape');
  assert.equal(await page.$('dialog[open]'), null);
  checks.push('Búsqueda vacía, favoritos persistentes y detalle accesible');
  await page.click('[data-nav="garage"]');
  assert.equal(await page.$$eval('.garage-grid .vehicle-card', cards => cards.length), 93);
  await page.type('#garage-search', 'infernus');
  assert.equal(await page.$$eval('.garage-grid .vehicle-card', cards => cards.length), 1);
  await page.click('.garage-grid .vehicle-card');
  assert.equal(await page.$eval('[data-filter="vehicle"]', select => select.value), 'Infernus');
  checks.push('Garaje y acceso a carreras por vehículo');
  await page.click('#clear-filters');
  await page.click('[data-nav="ranking"]');
  assert.equal(await page.$eval('.podium-0 h2', el => el.textContent), 'trustmeson');
  assert.equal(await page.$$eval('.ranking-table tbody tr', rows => rows.length), 21);
  await page.screenshot({ path: resolve(out, 'ranking.png'), fullPage: true });
  checks.push('Ranking completo con porcentajes');
  await writeFile(resolve(out, 'previous.json'), JSON.stringify([['1', 'A', 'Infernus', '10', 'PilotoAnterior', '01 Minutos 00:000 Segundos']]));
  await page.click('#data-button');
  await (await page.$('#import-previous')).uploadFile(resolve(out, 'previous.json'));
  await page.waitForFunction(() => document.querySelector('.ranking-table')?.textContent.includes('PilotoAnterior'));
  assert.match(await page.$eval('.ranking-table', el => el.textContent), /-1/);
  checks.push('Comparación muestra al piloto que pierde todos sus récords');
  await page.click('#data-button');
  await page.click('#reset-data');
  await writeFile(resolve(out, 'invalid.txt'), 'archivo no válido');
  await page.click('#data-button');
  await (await page.$('#import-current')).uploadFile(resolve(out, 'invalid.txt'));
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('JSON válido'));
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '1.020');
  await page.keyboard.press('Escape');
  checks.push('Importación inválida no reemplaza los datos');
  const dangerous = '<img src=x onerror="window.injected=true">';
  await writeFile(resolve(out, 'unsafe.json'), JSON.stringify({ races: [{ id: '1', name: dangerous, vehicle: 'Sultan', checkpoints: 10, holder: 'Test', timeMs: 60000 }], capturedAt: 'invalid' }));
  await page.click('#data-button');
  await (await page.$('#import-current')).uploadFile(resolve(out, 'unsafe.json'));
  await page.waitForFunction(() => document.querySelector('.race-name')?.textContent.includes('onerror'));
  assert.equal(await page.evaluate(() => window.injected), undefined);
  assert.equal(await page.$$eval('.race-name img', els => els.length), 0);
  await page.click('#data-button');await page.click('#reset-data');
  checks.push('Nombres importados se muestran como texto, sin ejecutar HTML');
  await page.setViewport({ width: 390, height: 844 });
  await page.screenshot({ path: resolve(out, 'mobile.png'), fullPage: true });
  const size = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }));
  assert.ok(size.scroll <= size.width, `Desbordamiento móvil: ${JSON.stringify(size)}`);
  await page.click('[data-nav="races"]');
  await page.type('#race-search', 'Voodoo');
  assert.equal(await page.$eval('.results-toolbar strong', el => el.textContent), '33');
  await page.click('#clear-filters');
  await page.click('.race-name');
  assert.ok(await page.$('dialog[open]'));
  await page.keyboard.press('Escape');
  checks.push('Móvil de 390 px: sin desbordamiento, búsqueda y diálogos');
  const denied = await fetch('http://127.0.0.1:3100/.env');
  assert.equal(denied.status, 403);
  const source = await fetch('http://127.0.0.1:3100/index.js');
  assert.equal(source.status, 404);
  assert.deepEqual(errors, []);
  checks.push('Servidor restringido a archivos públicos y sin errores JS');
  console.log(checks.map((check, i) => `${i + 1}. OK ${check}`).join('\n'));
  await writeFile(resolve(out, 'browser-results.json'), JSON.stringify({ checks, errors }, null, 2));
} finally {
  await browser?.close();
  server.kill();
}
